const Menu = [
    {
        id: 1,
        image: "https://captionsgram.com/wp-content/uploads/2021/02/Maggie-Captions-for-Instagram.jpg",
        name: "MAGGIE",
        category: "Snacks",
        price:"20 rupees",
        description:"Maggi is not a food, It’s an Emotion.",
    },
    {
        id: 2,
        image: "https://www.sharmispassions.com/wp-content/uploads/2020/12/idli12-460x500.jpg",
        name: "IDILE",
        category: "Breakfast",
        price:"20 rupees",
        description:"Idli is one dish that can never get boring.",
    },
    {
        id: 3,
        image: "https://5.imimg.com/data5/HW/II/SH/SELLER-9770898/veg-thali-500x500.jpg",
        name: "VEG-THALI",
        category: "Lunch",
        price:"60 rupees",
        description:"A Thali is all you need ",
    },
    {
        id: 4,
        image: "https://www.shutterstock.com/image-photo/paneer-butter-masala-indian-cuisin-260nw-1035164929.jpg",
        name: "ROTI & KHADAI-PANEER",
        category: "Dinner",
        price:"180 rupees",
        description:"Enjoy the flovor of yummy khadai-paneer",
    },
    {
        id: 5,
        image: "https://img.onmanorama.com/content/dam/mm/en/food/features/images/2021/10/17/pizza.jpg.transform/schema-16x9/image.jpg",
        name: "PIZZA",
        category: "Snacks",
        price:"120 rupees",
        description:"A slice a day keeps the sad day away",
    },
    {
        id: 6,
        image: "https://cdn.urbanpiper.com/media/bizmedia/2022/12/29/G2OQ8q-BJYB2LnjLWhWEe7lpgf1CuRlfggJ9pImjFwNOVaF.jpg",
        name: "NON-VEG THALI",
        category: "Lunch",
        price:"90 rupees",
        description:"Full of tasty items",
    },
    {
        id: 7,
        image: "https://www.ticklingpalates.com/wp-content/uploads/2022/03/plain-dosa.jpg",
        name: "DOSA",
        category: "Breakfast",
        price:"50 rupees",
        description:"crunchy dosa along with the aroma of chutney and sambhar",
    },
    {
        id: 8,
        image: "https://www.chewoutloud.com/wp-content/uploads/2021/05/lo-mein-square-500x500.jpg",
        name: "NOODLES",
        category: "Snacks",
        price:"40 rupees",
        description:"Keep calm and eat ramen",
    },
    {
        id: 9,
        image: "https://i.redd.it/lm8md0cq8kf51.jpg",
        name: "BUTTER-NAN & CHICKEN",
        category: "Dinner",
        price:"180 rupees",
        description:"Dear Butter chicken are sweet, spicy and inviting.",
    },
    {
        id: 10,
        image: "https://www.indianhealthyrecipes.com/wp-content/uploads/2020/12/fried-rice.jpg",
        name: "FRIED RICE",
        category: "Dinner",
        price:"50 rupees",
        description:"Everything is better with fried rice ",
    },
    {
        id: 11,
        image: "https://www.cubesnjuliennes.com/wp-content/uploads/2020/07/Chicken-Biryani-Recipe.jpg",
        name: "BIRYANI",
        category: "Dinner",
        price:"80 rupees",
        description:"“Biryani is nothing but, just a state of happiness”.",
    },
    {
        id: 12,
        image: "https://wirally.com/wp-content/uploads/2019/11/1-Thali-Places-In-Hyderabad.jpg",
        name: "SOUTH INDIAN THALI",
        category: "Lunch",
        price:"70 rupees",
        description:"Fill with goodness from south",
    },
    {
        id: 13,
        image: "https://thumbs.dreamstime.com/b/tasty-north-indian-thali-plate-jaipur-rajasthan-indian-rajasthani-thali-plate-111728068.jpg",
        name: "NORTH INDIAN THALI",
        category: "Lunch",
        price:"70 rupees",
        description:"All north ka taste",
    },
    {
        id: 14,
        image: "https://asmallbite.com/wp-content/uploads/2017/11/Aloo-Paratha-Recipe.jpg",
        name: "ALOO PARATHA",
        category: "Dinner",
        price:"50 rupees",
        description:"Everybody loves them!",
    },
    {
        id: 15,
        image: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcRLO1oIoR8guT4YK9j21MjUX9RBWty4Ga1KjA&usqp=CAU",
        name: "MOMO",
        category: "Snacks",
        price:"30 rupees",
        description:"“Eat, sleep and repeat”",
    },
    {
        id: 16,
        image: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcSUA3Vrr4HiBmzikVu11azNce7-CSEPCfqRJA&usqp=CAU",
        name: "UPMA",
        category: "Breakfast",
        price:"20 rupees",
        description:"It can't get healthier + tasty than this",
    },
    {
        id: 17,
        image: "https://c8.alamy.com/comp/BG78XB/chocolates-sweets-candy-BG78XB.jpg",
        name: "CHOCOLATES",
        category: "Timepass",
        price:"1-150 rupees",
        description:"Life is like a box of chocolates. ...",
    },
    
]

export default Menu;